import type { Metadata } from "next";
import "./globals.css";
import { getLocale, getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import MainProvider from "@/rtk/MainProvider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Review",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"} data-scroll-behavior="smooth">
      <body
        className={`font-expo`}
      >
        <Toaster position="bottom-right" />
        <NextIntlClientProvider messages={messages}>
            <MainProvider lang={locale ?? "en"}>{children}</MainProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
