import type { Metadata } from "next";
import { Poppins, Readex_Pro } from "next/font/google";
import "./globals.css";
import { getLocale, getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import MainProvider from "@/rtk/MainProvider";
import { cookies } from "next/headers";
import { Toaster } from "sonner";
import { AuthProvider } from "@/context/AuthContext";

const poppins = Poppins({
  weight: ["200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

const readex = Readex_Pro({
  subsets: ["arabic"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Wafferha",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  const token = (await cookies()).get("token")?.value || null;
  const role = (await cookies()).get("roles")?.value || null;

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"} data-scroll-behavior="smooth">
      <body
        className={`font-expo`}
      >
        <Toaster position="bottom-right" />
        <NextIntlClientProvider messages={messages}>
          <AuthProvider initialToken={token} initialRole={role}>
            <MainProvider lang={locale ?? "en"}>{children}</MainProvider>
          </AuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
